name: Update LeetCode Feed

on:
  schedule:
    - cron: "*/30 * * * *"   # updates every 30 minutes
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Profile Repo
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Fetch Latest LeetCode Solves
        run: |
          echo "<ul>" > lc_feed.txt
          curl -s "https://api.github.com/repos/LFDECO/Leetcode-solutions/commits?per_page=7" \
          | jq -r '.[] | "<li>✅ <b>" + (.commit.message | gsub("\n"; " ")) + "</b></li>"' \
          >> lc_feed.txt
          echo "</ul>" >> lc_feed.txt

      - name: Update README Section
        run: |
          perl -0777 -i -pe 's/<!-- LEETCODE_SOLVES:START -->.*<!-- LEETCODE_SOLVES:END -->/<!-- LEETCODE_SOLVES:START -->\n'"$(cat lc_feed.txt)"'\n<!-- LEETCODE_SOLVES:END -->/s' README.md

      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md
          git commit -m "Updated LeetCode feed" || exit 0
          git push
